services:
  app:
    build: .
    ports:
      - "1999:1999"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - PARTY_HOST=http://localhost:1999
      - NODE_ENV=development
    command: npm run dev
