version: 2.1

orbs:
  node: circleci/node@5.1.0

jobs:
  build-and-test:
    docker:
      - image: cimg/node:22.0
    steps:
      - checkout

      # Install dependencies
      - node/install-packages:
          pkg-manager: npm
      
      # Test application startup (catches runtime compatibility issues)
      - run:
          name: Test Application Startup
          command: |
            echo "Testing application can start without runtime errors..."
            npm run dev &
            SERVER_PID=$!
            sleep 10
            if kill -0 $SERVER_PID 2>/dev/null; then
              echo "✓ Application startup test passed!"
              kill $SERVER_PID
            else
              echo "✗ ERROR: Application failed to start"
              exit 1
            fi
      
      # Build and validate PartyKit server code
      - run:
          name: Build PartyKit Server
          command: |
            npm run build
            echo "PartyKit server build successful!"
      
      # Build web extension to ensure it compiles
      - run:
          name: Build Web Extension
          command: |
            export NODE_ENV=production
            export PARTY_HOST=${PARTY_HOST:-"https://github-party.partykit.dev"}
            npm run build:extension
            echo "Web extension build successful!"

  deploy:
    docker:
      - image: cimg/node:22.0
    steps:
      - checkout
      
      # Install dependencies
      - node/install-packages:
          pkg-manager: npm
      
      # Deploy to PartyKit
      - run:
          name: Deploy to PartyKit
          command: |
            npm run deploy
      
      # Build the web extension with static PartyKit URL
      - run:
          name: Build web extension
          command: |
            export NODE_ENV=production
            export PARTY_HOST="https://multiplayer-github.willtcarey.partykit.dev"
            npm run build:extension
      
      # Store web extension build artifacts
      - store_artifacts:
          path: web-extension-dist
          destination: web-extension

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-and-test:
          context:
            - partykit-deploy
          filters:
            branches:
              ignore:
                - main
      
      - deploy:
          context:
            - partykit-deploy
          filters:
            branches:
              only:
                - main
