version: 2.1

orbs:
  node: circleci/node@5.1.0

jobs:
  build-and-deploy:
    docker:
      - image: cimg/node:18.17
    steps:
      - checkout
      
      # Install dependencies
      - node/install-packages:
          pkg-manager: npm
      
      # Deploy to PartyKit first (only on main branch) to get the URL
      - run:
          name: Deploy to PartyKit
          command: |
            if [ "$CIRCLE_BRANCH" = "main" ]; then
              echo "Deploying to PartyKit..."
              # Set up PartyKit authentication
              echo "Setting up PartyKit authentication..."
              echo "$PARTYKIT_TOKEN" | npx partykit auth login --token
              
              # Deploy and capture the URL
              DEPLOY_OUTPUT=$(npm run deploy 2>&1)
              echo "$DEPLOY_OUTPUT"
              
              # Extract the PartyKit URL from deployment output
              PARTY_URL=$(echo "$DEPLOY_OUTPUT" | grep -o 'https://[^[:space:]]*\.partykit\.dev' | head -1)
              
              if [ -n "$PARTY_URL" ]; then
                echo "PartyKit deployed to: $PARTY_URL"
                echo "export DYNAMIC_PARTY_HOST=$PARTY_URL" >> $BASH_ENV
              else
                echo "Could not extract PartyKit URL from deployment output"
                # Fallback to environment variable if extraction fails
                echo "export DYNAMIC_PARTY_HOST=$PARTY_HOST" >> $BASH_ENV
              fi
            else
              echo "Skipping PartyKit deployment - not on main branch"
              # For non-main branches, use the environment variable
              echo "export DYNAMIC_PARTY_HOST=$PARTY_HOST" >> $BASH_ENV
            fi
      
      # Build the web extension with the real PartyKit URL
      - run:
          name: Build web extension
          command: |
            export NODE_ENV=production
            # Source the environment to get DYNAMIC_PARTY_HOST
            source $BASH_ENV
            export PARTY_HOST=$DYNAMIC_PARTY_HOST
            echo "Building extension with PARTY_HOST=$PARTY_HOST"
            npm run build:extension
      
      # Store web extension build artifacts
      - store_artifacts:
          path: web-extension-dist
          destination: web-extension

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-and-deploy:
          context:
            - partykit-deploy
          filters:
            branches:
              only:
                - main
                - /feature\/.*/
                - /hotfix\/.*/
